name: Exemple de workflow
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Dire bonjour
      uses: ./
      with:
        username: "Daria"
        greeting: "Salut"